---
- name: deploy httpd container
  hosts: all
  become: true
  gather_facts: false
  vars:
    webroot: "/webroot"
  tasks:


#    - name: Add repository - Microsoft
#      ansible.builtin.yum_repository:
#        name: podman
#        description: podman
#        baseurl: https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#        gpgcheck: false
#        enabled: true

#    - name: Install epel-release
#      ansible.builtin.yum:
#        name:
#          - amzn2extra-docker
#        state: disable
#        update_cache: true


#    - name: lazy installs
#      ansible.builtin.shell: "{{ item }}"
#      become: true
#      loop:
#        - yum-config-manager --disable amzn2extra-docker
#        - yum -y install https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#        - curl -L -o /etc/yum.repos.d/devel:kubic:libcontainers:stable.repo https://download.opensuse.org/repositories/devel:/kubic:/libcontainers:/stable/CentOS_7/devel:kubic:libcontainers:stable.repo
#        - yum -y install yum-plugin-copr
#        - yum -y copr enable lsm5/container-selinux


#    - name: Install Packages
#      ansible.builtin.yum:
#        state: latest
#        name:
#          - https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
#          - yum-plugin-copr
#
    - name: podman installed
      ansible.builtin.yum:
        name: podman
        state: latest

    - name: pull image
      containers.podman.podman_image:
        name: httpd
        pull: true
        tag: latest

    - name: webroot present
      ansible.builtin.file:
        path: "{{ webroot }}"
        state: directory
        owner: "root"
        group: "root"
        mode: '0777'
        setype: "container_share_t"

    - name: custom index.html
      ansible.builtin.copy:
        dest: "{{ webroot }}/index.html"
        content: |
                    Custom Web Page
        setype: "container_share_t"

    - name: run httpd container
      containers.podman.podman_container:
        name: webserver
        image: httpd
        state: started
        detach: true
        expose:
          - 80
        ports:
          - 8080:80
        volume:
          - "{{ webroot }}:/usr/local/apache2/htdocs/:exec"
      register: rhc

    - name: Gather facts on a specific container
      containers.podman.podman_container_info:
        name: webserver
      register: rhci

    - debug:
        msg: 
          - "{{ rhc }}"
          - "{{ rhc.stdout_lines }}"
          - "{{ rhci }}"
          - "{{ rhci.stdout_lines }}"


